import { ApplicationConfig, provideBrowserGlobalErrorListeners, provideZoneChangeDetection, importProvidersFrom } from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { LucideAngularModule } from 'lucide-angular';

// ── Selective Lucide icon imports (tree-shakeable) ──────────
import {
  Activity,
  AlertTriangle,
  BadgeCheck,
  BadgeDollarSign,
  Ban,
  Bookmark,
  Calculator,
  ChartColumn,
  ChartLine,
  ChartNoAxesCombined,
  ChartPie,
  Check,
  CheckCircle,
  ChevronDown,
  CircleAlert,
  CircleCheck,
  CirclePlus,
  CircleUser,
  Clipboard,
  ClipboardList,
  ClipboardX,
  Clock,
  CreditCard,
  DollarSign,
  Download,
  FileText,
  Inbox,
  Info,
  Key,
  List,
  LoaderCircle,
  Lock,
  LogOut,
  Logs,
  Mail,
  Monitor,
  MonitorX,
  Moon,
  Package,
  PackageX,
  Palette,
  Pencil,
  Plus,
  Printer,
  Receipt,
  RefreshCw,
  Save,
  Search,
  Settings,
  Shield,
  ShoppingBag,
  ShoppingCart,
  SlidersHorizontal,
  Star,
  Sun,
  Trash2,
  TrendingUp,
  TrendingUpDown,
  TriangleAlert,
  User,
  UserCheck,
  UserPlus,
  Users,
  X,
} from 'lucide-angular';

import { routes } from './app.routes';
import { authInterceptor } from './auth/auth.interceptor';

const lucideIcons = {
  Activity,
  AlertTriangle,
  BadgeCheck,
  BadgeDollarSign,
  Ban,
  Bookmark,
  Calculator,
  ChartColumn,
  ChartLine,
  ChartNoAxesCombined,
  ChartPie,
  Check,
  CheckCircle,
  ChevronDown,
  CircleAlert,
  CircleCheck,
  CirclePlus,
  CircleUser,
  Clipboard,
  ClipboardList,
  ClipboardX,
  Clock,
  CreditCard,
  DollarSign,
  Download,
  FileText,
  Inbox,
  Info,
  Key,
  List,
  LoaderCircle,
  Lock,
  LogOut,
  Logs,
  Mail,
  Monitor,
  MonitorX,
  Moon,
  Package,
  PackageX,
  Palette,
  Pencil,
  Plus,
  Printer,
  Receipt,
  RefreshCw,
  Save,
  Search,
  Settings,
  Shield,
  ShoppingBag,
  ShoppingCart,
  SlidersHorizontal,
  Star,
  Sun,
  Trash2,
  TrendingUp,
  TrendingUpDown,
  TriangleAlert,
  User,
  UserCheck,
  UserPlus,
  Users,
  X,
};

export const appConfig: ApplicationConfig = {
  providers: [
    importProvidersFrom(LucideAngularModule.pick(lucideIcons)),
    provideBrowserGlobalErrorListeners(),
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(routes),
    provideHttpClient(withInterceptors([authInterceptor])),
  ],
};
