@BASE_URL = http://localhost:3000
@ADMIN_TOKEN =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU2ZTdmMzU0LTM0MzgtNGZlOC1iZWY0LTZjMTU5ZDhmNTYwMiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc3MDk3MTEyNiwiZXhwIjoxNzcxNTc1OTI2fQ._goppepGpEIm5mnvp12H8OFXaZDhky5l8RwfA1mAnYU
@USER_TOKEN =
@CATEGORY_ID =17107080-2320-4b5f-82bb-d7bac5f93b78
@BRAND_ID =39e7f0dc-cbd6-46e6-958b-7e44263d304e

### 1) Health
GET {{BASE_URL}}/health

### 2) Register admin
POST {{BASE_URL}}/auth/register
Content-Type: application/json

{
  "email": "admin2@test.com",
  "username": "admin2",
  "password": "TestPass1234!",
  "fullname": "System Admin1",
  "role": "admin"
}

### 3) Login admin
POST {{BASE_URL}}/auth/login
Content-Type: application/json

{
  "email": "admin2@test.com",
  "password": "TestPass1234!"
}

### 4) /me with token
GET {{BASE_URL}}/me
Authorization: Bearer {{ADMIN_TOKEN}}

### 5) Create item (ADMIN ONLY)
POST {{BASE_URL}}/items
Authorization: Bearer {{ADMIN_TOKEN}}
Content-Type: application/json

{
  "name": "Laptop X",
  "amount": 5,
  "category_id": "{{CATEGORY_ID}}",
  "brand_id": "{{BRAND_ID}}",
  "model": "X1000",
  "specifications": "16GB RAM",
  "warranty": "2 years"
}

### 6) List items
GET {{BASE_URL}}/items

### 7) Negative test (no token)
GET {{BASE_URL}}/me

### 8) Wrong password
POST {{BASE_URL}}/auth/login
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "WrongPassword"
}